{% set name = "macchina" %}
{% set version = "6.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Macchina-CLI/macchina/archive/v{{ version }}.tar.gz
  sha256: e827f640b55fe47a6127dd0c276e76b597e3cb83916be37351cdd6a81d75311e

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - macchina --help

about:
  home: https://github.com/Macchina-CLI/macchina
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: System information fetcher, with an emphasis on performance and minimalism
  dev_url: https://github.com/Macchina-CLI/macchina

extra:
  recipe-maintainers:
    - danielnachun
