{% set name = "macchina" %}
{% set version = "6.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Macchina-CLI/macchina/archive/v{{ version }}.tar.gz
  sha256: 385bccc02f67c9ed6b9a483dbebdec901eb4beb82b15bb7969ee36028c19e475

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - macchina --help

about:
  home: https://github.com/Macchina-CLI/macchina
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: System information fetcher, with an emphasis on performance and minimalism
  dev_url: https://github.com/Macchina-CLI/macchina

extra:
  recipe-maintainers:
    - danielnachun
